### ISSUE TITLE
Check template files to make sure they reference variables instead of methods

### ISSUE THREAD

**Issue by vrillusions** [rodjek/puppet-lint#204]
Per http://docs.puppetlabs.com/guides/templating.html#referencing-variables this (this probably doesn't work as is but it should give you an idea):

``` puppet
file { '/etc/resolv.conf':
  ensure  => file,
  content => template("search <%= domain %>"),
}
```

Logs deprecation notices in puppet 3 and is going to be removed in puppet 4.  It should be written as

``` puppet
file { '/etc/resolv.conf':
  ensure  => file,
  content => template("search <%= @domain %>"),
}
```

In short `<%= variable_name %>`(method call) should be `<%= @variable_name %>`(variable call).

**Comment by rnelson0** [comment]
As presented, this is a syntax issue, not a style guide compatibility issue. As the puppet language grows more complex, recreating parts of it in puppet-lint becomes more dangerous. I'm going to close this out, but if someone wants to create a PR against the 3.0.0 branch that leverages the puppet4 parser/lexer API to parse template contents, we can definitely review it though.
