### ISSUE TITLE
Autoloader layout test fails inside a (custom named) module directory

### ISSUE THREAD

**Issue by mechanicalduck** [rodjek/puppet-lint#265]
This bug / problem applies to all puppet-lint versions, including 0.4.0.pre1.

When puppet-lint is invoked inside a module directory and the module directory isn't named exactly like the module name, the autoloader layout test will always report failure although directory structure, file names and code are correct.

A module directory named exactly as the module isn't a necessity in practice, for example, either the org name is prepended ('_org-name_-_module-name_/') or a complete deviation from usual naming is used, e.g. when it is a build directory named to a CI build job ('_org-name_-_module-name_\_build/').

It is unusual and it should be unnecessary explicitly using an extra directory, named as the module, inside the module repository ('_module-name_/{_manifests_;_templates_;_..._}') for passing the puppet-lint autoloader layout test.

See: https://github.com/rodjek/puppet-lint/blob/master/lib/puppet-lint/plugins/check_classes.rb#L27

(Paths below relative to puppet-lint cwd)
Fails autoloader layout test:
Example 1:
./manifests/
./manifests/test/
./manifests/test/init.pp

Example 2:
./_some-name_/manifests/
./_some-name_/manifests/test/
./_some-name_/manifests/test/init.pp

Passes autoloader layout test:
./_module-name_/
./_module-name_/manifests/
./_module-name_/manifests/test/
./_module-name_/manifests/test/init.pp

**Comment by rnelson0** [comment]
This was resolved in #334. Please open a new ticket if you encounter a regression. Thank you!
