### ISSUE TITLE
"puppet:// URL without modules/" - in the style guide?  Custom mount points?

### ISSUE THREAD

**Issue by astrostl** [rodjek/puppet-lint#307]
I recently upgraded, and ran into http://puppet-lint.com/checks/puppet_url_without_modules/

Searching for 'modules' and 'url' and such, I don't see this requirement in https://docs.puppetlabs.com/guides/style_guide.html

Furthermore, it is throwing warnings on my setup with documentation-correct custom mount points: https://docs.puppetlabs.com/guides/file_serving.html#serving-files-from-custom-mount-points

I know it can be disabled, and I am disabling it.  Should this exist, or be on by default, though?

**Comment by rnelson0** [comment]
@jflorian Will #406 help with this issue?

**Comment by rnelson0** [comment]
@jflorian I am closing this ticket but feel free to re-open it or open a new one if need be. Thanks!
