### ISSUE TITLE
--fix doesn't change "\$var" to single-quotes

### ISSUE THREAD

**Issue by alexjurkiewicz** [rodjek/puppet-lint#313]
Example:

    $ cat test.pp
    $var = " \$foo"
    $ puppet-lint --fix test.pp
    $ cat test.pp
    $var = " \$foo "

Expected `$var = ' $foo '`

**Comment by rodjek** [comment]
Yeah, as @mark0n stated, puppet-lint can't detect intention so it prefers to keep these strings as double quoted with the `$` escaped in favour of detecting accidental variable use in single quoted strings.
