### ISSUE TITLE
Separate checks for style guide 9.2 (arrow_alignment)

### ISSUE THREAD

**Issue by hgoodman** [rodjek/puppet-lint#348]
Style guide section 9.2 specifies two distinct requirements:
- All of the fat comma arrows [...] should be aligned.
- The arrows should be placed one space ahead of the longest attribute name.

I propose that separate checks be added (in addition to arrow_alignment, which would combine the two) in order to give the user granular control to enforce one requirement but not the other.

Is this something that would be acceptable to add to the core of puppet-lint? Would a check that is _only_ for fat comma alignment be suitable for a community plugin? Is this even the right place to be asking these questions? (Sorry, I'm new here)

**Comment by rnelson0** [comment]
@hgoodman It's been a while since you submitted this. Are you still interested in pursuing this, or have you found other custom checks that address this already?

**Comment by hgoodman** [comment]
I still think it's a good idea since I prefer to align not just fat arrows within a resource declaration, but also across related resource declarations.

That being said, I haven't done much Puppet development lately, so personally speaking, I'm somewhat indifferent.

**Comment by rnelson0** [comment]
I think this would be good but is unlikely to be developed currently without a volunteer so I am closing it. Please feel free to re-open it if you have the time @hgoodman. Thanks!
