### ISSUE TITLE
Puppet lint should warn on semi colon usage when used without compression

### ISSUE THREAD

**Issue by dkerratfanduel** [rodjek/puppet-lint#367]
Hi there.

If a semi colon is used without compression I feel that this should be a presented as a linting error i.e.

file { "/tmp/a":
	mode => 700,
	content => "a";
}

Should be written as

file { "/tmp/a":
	mode => 700,
	content => "a";
}

According to https://docs.puppetlabs.com/guides/style_guide.html#compression

**Comment by rnelson0** [comment]
Compression is no longer mentioned in the style guide. Is there another item in the guide this would be associated with?

**Comment by rnelson0** [comment]
@dkerratfanduel I am closing this out but feel free to re-open or open a new ticket if you need to. Thanks!
