### ISSUE TITLE
Puppet-lint for EPEL7

### ISSUE THREAD

**Issue by butterhc** [rodjek/puppet-lint#372]
Is it possible for puppet-lint be added to EPEL7? It was so nice to have it in EPEL6.

Thanks!

**Comment by rodjek** [comment]
I didn't maintain the the EPEL6 package for puppet-lint. Actually, I don't use RedHat/CentOS/Fedora either personally or professionally so I'm probably not the best person to be maintaining that package. Perhaps you could contact the maintainer of the EPEL6 package and see if he or she would be interested in building it for EPEL7 too?
