### ISSUE TITLE
Looking for a tool that shows the output of puppet-lint and rspec-puppet on a screen like jenkins

### ISSUE THREAD

**Issue by 030** [rodjek/puppet-lint#374]
Is it possible to check the Puppet code using Jenkins or something? Would it be possible to indicate that the build fails by interpreting the outcome of puppet-lint and rspec-puppet?

The aim is to run a kind of build once changes have been made to the Puppet code. Puppet-lint and rspec-puppet are helpfull, but is it possible to visualize it on a screen like Jenkins does? 

If false would it be an idea to create a new project or extend the rspec-puppet and puppet-lint with this?

**Comment by rnelson0** [comment]
This request is a bit out of scope for puppet-lint, closing.
