### ISSUE TITLE
file modes doesn't have to be 4 digit octal

### ISSUE THREAD

**Issue by mat-mo** [rodjek/puppet-lint#394]
The file mode warning says: WARNING mode should be represented as a 4 digit octal value or symbolic mode
But file modes don't have to be 4 digits. 02755 or 01777 are 100% valid file modes.
It seems like the source of confusion is https://docs.puppetlabs.com/references/latest/type.html#file-attribute-mode which says: Numeric modes should use the standard four-digit octal notation of <setuid/setgid/sticky><owner><group><other> (e.g. 0644)
I'll open a bug against the doc as well.

**Comment by mat-mo** [comment]
see also: https://github.com/puppetlabs/puppet-docs/pull/453

**Comment by Aethylred** [comment]
The linter is not about what Puppet considers as valid syntax. but what the puppet Style Guide considers to be good form.

4 Digit file modes are recommended: https://docs.puppetlabs.com/guides/style_guide.html#file-modes

**Comment by rnelson0** [comment]
@mat-mo Would a control comment suffice for your needs, as the linter is complying with the style guide?

**Comment by mat-mo** [comment]
From my point of view this can be closed. I understand the linter doesn't care for valid file modes, but for recommended ones. Thanks

**Comment by rnelson0** [comment]
Thanks for the update!
