### ISSUE TITLE
approach to supporting puppet style guide v2

### ISSUE THREAD

**Issue by ghoneycutt** [rodjek/puppet-lint#398]
@rodjek 

We previously chatted about this approach, but since the style guide never really changed, there was no need to implement it. Now that there is a new one, thought I would refresh this idea. Especially with Puppet v4 soon on the way with its many language changes, which will result in another new style guide.
- Keep all of the old checks for those that are still compliant to v1 of the style guide.
- Create new checks for the new guide.
- Create metaparameters such as --v1 and --v2 that will associate all of the checks applicable to each major version of the style guide. ie: --v1 would include '80chars-check' while --v2 would include '140chars-check'.
- Given that v2 of the style guide is not radically different from v1 and the desire to promote the new version of the style guide, puppet-lint should default to using checks from v2.

**Comment by ghoneycutt** [comment]
@rodjek What are your thoughts on this?

**Comment by tuxinaut** [comment]
:+1:

**Comment by strider** [comment]
:+1:

**Comment by rnelson0** [comment]
@ghoneycutt Are you interested in taking this back up again? Some of us are going to work on puppet-lint at next week's Puppethack, perhaps we can work up a list then and start on the work.

**Comment by rnelson0** [comment]
@ghoneycutt I think we are handling most of these concerns in other issues and PRs. Do you feel there is still work that has is not in the process of being addressed elsewhere, or can we close this ticket?

**Comment by rnelson0** [comment]
I'm going to close this out for now. Thanks!
