### ISSUE TITLE
Disabled checks aren't actually disabled, output is merely ignored.

### ISSUE THREAD

**Issue by pcbadger** [rodjek/puppet-lint#400]
I'm on puppet-lint 1.1.0, running tests via rakefile. Since upgrading recently (from .6 or something) i've noticed a long pause during the lint tests. On a hunch, I removed the disable checks lines from the rakefile. Wether or not the tests are disabled, it takes 1:50 seconds to move from step3 to step 4 in my rakefile, before the upgrade it took a lot less time, certainly under 30 seconds. It looks like it's still running the tests in the background, just not outputting anything.

Is it just me? Is there any way to get it to explicitly not run these checks?

**Comment by rnelson0** [comment]
The checks should not be run, as the enabled checks are discovered [here](https://github.com/rodjek/puppet-lint/blob/a1de8eaaf4a8fff5b82af1bb3e93b918675e4e18/lib/puppet-lint/checks.rb#L79-L81) and then [iterated over](https://github.com/rodjek/puppet-lint/blob/a1de8eaaf4a8fff5b82af1bb3e93b918675e4e18/lib/puppet-lint/checks.rb#L56).
