### ISSUE TITLE
puppet-lint still checks for lines with more than 80 character

### ISSUE THREAD

**Issue by EslamElHusseiny** [rodjek/puppet-lint#425]
As far I understood from the PuppetLabs style guide website https://docs.puppetlabs.com/guides/style_guide.html#spacing-indentation-and-whitespace , each line should be no-longer than 140 characters instead of 80 characters.

**Comment by rothsa** [comment]
@EslamElHusseiny you're correct, when https://github.com/rodjek/puppet-lint/pull/419 is merged it will be  updated :)
