### ISSUE TITLE
Check for unbalanced parenthesis

### ISSUE THREAD

**Issue by squiddle** [rodjek/puppet-lint#427]
It would be nice if puppet-lint could catch unbalanced parenthesis. Puppet will catch them anyway, but it would be nice for a linter to check this.

**Comment by ghoneycutt** [comment]
Hi,

That is a syntax issue, not a lint issue. You can create your own puppet-lint plugin, such as

https://github.com/puppet-community/puppet-lint-appends-check

Best,
-g

**Comment by rnelson0** [comment]
Validating the puppet code is best left to `puppet parser validate`. Thank you.
