### ISSUE TITLE
url_without_modules adding paths?

### ISSUE THREAD

**Issue by rgevaert** [rodjek/puppet-lint#428]
Hi,

I have an extra fileserver mount in my puppet config.  How can I add that to the url_without_modules check?  Is that possible?

Thanks

**Comment by rnelson0** [comment]
@rgevaert Will #406 address your concerns?

**Comment by rgevaert** [comment]
Yes!!

**Comment by rnelson0** [comment]
Ok, I am going to close this as a duplicate. Thanks!
