### ISSUE TITLE
heredoc escape gives syntax error

### ISSUE THREAD

**Issue by cynipe** [rodjek/puppet-lint#430]
Seems like puppet-lint does not support all of the syntax of heredoc.

```
$ cat heredoc.pp
$value = 'foo'
notice @("EOF":json/$)
  {
    "hoge": "${value}"
  }
  |-EOF

$ bundle exec puppet apply heredoc.pp
Notice: Scope(Class[main]): {
  "hoge": "foo"
}
Notice: Compiled catalog for st-okamoto-m.local in environment production in 0.31 seconds
Notice: Applied catalog in 0.01 seconds

$ bundle exec puppet-lint heredoc.pp
ERROR: Syntax error (try running `puppet parser validate <file>`) on line 2
```

puppet version: 4.1.0
puppet-lint Current HEAD(2546fed6be894bbcff15c3f48d4b6f6bc15d94d1)

**Comment by PiotrCzapla** [comment]
same on puppet-lint 1.1.0

**Comment by rnelson0** [comment]
This isn't anywhere near ready, but a first draft at parsing heredocs can be seen at https://github.com/rodjek/puppet-lint/compare/master...rnelson0:heredoc?expand=1.

**Comment by jhoblitt** [comment]
This seems to still be present with `2.0.2`:

```sh
$ bundle exec puppet --version
4.8.1
$ bundle exec puppet-lint --version
puppet-lint 2.0.2
$ cat test.pp
$foo = @("EOT"/$)
  \$bar
|EOT
$ bundle exec puppet apply test.pp
Notice: Compiled catalog for leo... in environment production in 0.02 seconds
Notice: Applied catalog in 0.03 seconds
$ bundle exec puppet-lint test.pp 
ERROR: Syntax error (try running `puppet parser validate <file>`) on line 1
```

**Comment by rnelson0** [comment]
@jhoblitt I don't think the heredoc parser will be up to snuff until 3.x; it's certainly not merged into 2.. Can you try the `rnelson0:heredoc` branch and see how that works for you? I would not be eager to merge it since it's kind of hacky and there isn't another workaround right now, but obviously puppet-lint falling on its face is not good either, so first thing is to find out if it works for your heredoc permutation with accuracy.

**Comment by jhoblitt** [comment]
@rnelson0 I gave it a try.  For some reason I had to remove `--no-80chars-check` from my rc file.

```ruby
  gem 'puppet-lint',
    :git => 'https://github.com/rnelson0/puppet-lint',
    :ref => 'heredoc'
```
```sh
/home/jhoblitt/github/sandbox-jenkins-demo-test/jenkins_demo/.bundle/ruby/2.1.0/bundler/gems/puppet-lint-a16562aed201/lib/puppet-lint/optparser.rb:110:in `block in build': invalid option: --no-80chars-check (OptionParser::InvalidOption)
	from /home/jhoblitt/github/sandbox-jenkins-demo-test/jenkins_demo/.bundle/ruby/2.1.0/bundler/gems/puppet-lint-a16562aed201/lib/puppet-lint/optparser.rb:21:in `new'
	from /home/jhoblitt/github/sandbox-jenkins-demo-test/jenkins_demo/.bundle/ruby/2.1.0/bundler/gems/puppet-lint-a16562aed201/lib/puppet-lint/optparser.rb:21:in `build'
	from /home/jhoblitt/github/sandbox-jenkins-demo-test/jenkins_demo/.bundle/ruby/2.1.0/bundler/gems/puppet-lint-a16562aed201/lib/puppet-lint/bin.rb:22:in `run'
	from /home/jhoblitt/github/sandbox-jenkins-demo-test/jenkins_demo/.bundle/ruby/2.1.0/bundler/gems/puppet-lint-a16562aed201/bin/puppet-lint:7:in `<top (required)>'
	from /home/jhoblitt/github/sandbox-jenkins-demo-test/jenkins_demo/.bundle/ruby/2.1.0/bin/puppet-lint:23:in `load'
	from /home/jhoblitt/github/sandbox-jenkins-demo-test/jenkins_demo/.bundle/ruby/2.1.0/bin/puppet-lint:23:in `<main>'
```
```sh
bundle exec puppet-lint test.pp 
ERROR: Syntax error (try running `puppet parser validate <file>`) on line 1
```

**Comment by jhoblitt** [comment]
@rnelson0 I share your hesitant to leap to a new parser before it's well baked.  Perhaps a mechanism to simply not try to check/parse between two comment-tokens?

**Comment by rnelson0** [comment]
Oh, I can rebase that at least, I think 80char was replaced with 140char, then added in but disabled for compatibility and I must have mocked this up in between. Shame it doesn't work - there's just a lot of heredoc permutations :(

Are you envisioning something like this?
```
$value = 'foo'
#lint:ignore:all
notice @("EOF":json/$)
  {
    "hoge": "${value}"
  }
  |-EOF
#lint:endignore:all
```

**Comment by rnelson0** [comment]
It won't change the results but I rebased it so your lint config shouldn't conflict anymore.

**Comment by jhoblitt** [comment]
@rnelson0 Yes, that syntax is along the lines of what I was thinking.  Either `all` or `*` to disable everything seems fairly intuitive.

**Comment by rnelson0** [comment]
OK, let's work that in #585 and focus on the heredoc here.
