### ISSUE TITLE
Linter should not warn about inheriting from params class

### ISSUE THREAD

**Issue by pizzaops** [rodjek/puppet-lint#441]
http://puppet-lint.com/checks/class_inherits_from_params_class/

Puppet 2.6.2 is *long* EOL and backwards compatibility with that version is not important.

Inheriting from the params class is fine in Puppet 3 and Puppet 4.

**Comment by dioni21** [comment]
You can always use a $HOME/.puppet-lint.rc and disable it by default.

**Comment by pizzaops** [comment]
Yep, I'm aware, but it's an unnecessary feature at this point.

**Comment by binford2k** [comment]
We teach inheriting from the `params` class in Fundamentals now.

**Comment by ntent-ashton** [comment]
This is still a problem, any ETA for a permanent solution?

**Comment by derekmwright** [comment]
The out of the box functionality should be relevant for current supported platforms. We now have to disable this check for all team members that use puppet lint. Perhaps this could be moved to a "legacy" check and require a flag to invoke it rather than it being the norm.

**Comment by cvquesty** [comment]
Check out issue here:  https://github.com/rodjek/puppet-lint/pull/511

511 will solve this, I believe.  Comments?  Thoughts?

**Comment by rnelson0** [comment]
Yes, that does, and it can be accessed from HEAD or the forthcoming 2.1.0 release. Closing this out.
