### ISSUE TITLE
Bug with --fix and warning "variable not enclosed in {}"

### ISSUE THREAD

**Issue by Lucas-C** [rodjek/puppet-lint#442]
Hi,

Currently the `--fix` option incorrectly transform `$comp-$plateforme` into `${comp-}${plateforme}`.

If I submit a pull request with a bugfix, do you think you could include it in a release soon ?

Thanks

**Comment by rnelson0** [comment]
@Lucas-C If this is still an issue, we would gladly accept a PR for review. Thanks!

**Comment by Lucas-C** [comment]
PR sent ;)
