### ISSUE TITLE
Time for a new release!

### ISSUE THREAD

**Issue by faxm0dem** [rodjek/puppet-lint#443]
I stumbled on [an issue](http://stackoverflow.com/questions/27138893/puppet-lint-ignoring-the-ignore-paths-option) where my ignored paths were... ignored.
Please prepare a new release, thanks!

**Comment by Perdjesk** [comment]
+1 https://github.com/rodjek/puppet-lint/compare/1.1.0...master

A cleaning of issues would be welcomed too. #422 and #417 (maybe?) seem to have been fixed.

**Comment by stig** [comment]
+1 I am not able to use the `arrow_alignment` check because of #416, which is fixed in master.

**Comment by akerl** [comment]
Bump. Would rock to get a new release cut, I'm running into issues with the linter not checking my files that are fixed on master, as well as config.relative not being settable in the Rakefile

**Comment by keithherron** [comment]
+1

**Comment by mterzo** [comment]
+1

**Comment by Kriechi** [comment]
:+1:

**Comment by cyberious** [comment]
:+1: Overdue, if you don't want to maintain perhaps moving it to Puppet-Community or if somebody from PuppetLabs would want to take it over

**Comment by walkamongus** [comment]
:+1:

**Comment by albertux** [comment]
:+1:

**Comment by ghoneycutt** [comment]
Use this in your Gemfile to get the latest code.

``` ruby
gem 'puppet-lint', :git => 'https://github.com/rodjek/puppet-lint.git'
```

**Comment by cyberious** [comment]
I would prefer the latest releases in ruby gem and then we can also proxy these through artifactory or pulp instead of pulling from the internet at all times.

**Comment by albertux** [comment]
for now use @ghoneycutt solution if you are using Gemfile

if you are installing puppet-lint in your system use:

```ruby
gem install specific_install
gem specific_install -l https://github.com/rodjek/puppet-lint.git
```

**Comment by alexharv074** [comment]
+1

**Comment by rnelson0** [comment]
@rodjek Can you publish a new version of the gem, either 1.2.0 or 2.0.0?

**Comment by rmestrum** [comment]
@rodjek Can you please publish a new version of the gem

**Comment by rnelson0** [comment]
It looks like we can now release a new gem. The question is, what should the version number be? 1.1.1, 1.2.0, or 2.0.0?

I think there have been too many changes to be a point release, and that there are no backwards incompatible changes but I don't have a full history on the impact of all the changes to be sure of either. I'll start reviewing changes in detail but would like to hear others thoughts as well.

**Comment by rnelson0** [comment]
There are also some 71 Issues and 25 pull requests, but a lot of users are pulling from master so I'm confident it could be published as is. If there are any that you believe must be resolved before a new gem is published, please mention them here.

**Comment by Slm0n87** [comment]
+1

**Comment by albertux** [comment]
+1

**Comment by kylog** [comment]
@rnelson0 I agree that this isn't a 1.1.1. As for 1.2.0 vs 2.0.0, I took a scan through what's in master, and the only change that looked possibly to be breaking was https://github.com/rodjek/puppet-lint/pull/419, e.g. if someone were using `--no-80chars-check` or `PuppetLint.configuration.send("disable_80chars")`. 

Thoughts?

Mostly just psyched that we can release a new gem :)

**Comment by rnelson0** [comment]
That reduces the options to:

1. 1.2.0
2. 2.0.0

I don't see a way to do voting on GitHub. I am leaning toward 2.0.0 myself. If no-one has any complaints by Wednesday @ 1200 UTC, we'll push out version 2.0.0 to rubygems.

**Comment by ahpook** [comment]
@rnelson0 looks good to me, i added a +1 reaction to your post - if people have -1s they can give you a thumbs down!

**Comment by daenney** [comment]
I would prefer to see a 2.0.0 that included the necessary Puppet 4 related fixes but I guess that can be another bump.

**Comment by rnelson0** [comment]
@daenney I would too, but I think the backlog is pretty large right now and it's best to start the 2.x train then start merging them in as we clear it out.

**Comment by rnelson0** [comment]
Puppet-lint v2.0.0 is now available. Happy downloads! https://rubygems.org/gems/puppet-lint/versions/2.0.0

**Comment by rnelson0** [comment]
Thank you to everyone for your assistance in getting this release out!

**Comment by albertux** [comment]
Thank you @rnelson0
