### ISSUE TITLE
Single whitespace in file replaced with []

### ISSUE THREAD

**Issue by paskal** [rodjek/puppet-lint#444]
$subj, if file (init.pp in my case) have only single whitespace in it, with --fix it's removed by rule of trailing whitespace and replaced with [] somewhy.
Gem release (1.1.0) is not affected, only current master branch.
➜  internal  ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

**Comment by rnelson0** [comment]
This should be resolved in #469.
