### ISSUE TITLE
print warning for code that will result in logging or backups of secrets

### ISSUE THREAD

**Issue by jesseendahl** [rodjek/puppet-lint#455]
It would be great if puppet-lint could print a warning anytime it sees a puppet file resource that references a file containing what is likely to be a secret. If a hit was found, the warning could look something like this:

```
WARNING: Potentially insecure use of file resource. String `BEGIN PRIVATE KEY` found in file referenced by your file resource at line 20. Your current Puppet code will result in logging and backups of this file whenever its contents are updated by Puppet.

To prevent contents of this file from being written to log files, add the following line to the file resource:

show_diff => false,

To prevent filebucketing of this file, add the following line to the file resource:

backup    => false,
```

The linter would accomplish this by parsing the contents of files referenced by file resources and checking for various headers associated with secrets. For a start, looking for the string `BEGIN PRIVATE KEY` would catch both SSL and SSH private keys.

**Comment by ghoneycutt** [comment]
@jesseendahl Great idea though puppet-lint does static analysis on puppet manifests and does not have the capability to compile a catalog, which would be necessary to check the contents of a file. Suggest using a pre-commit hook or otherwise building the scan into your build pipeline to check for that in your code base.

**Comment by binford2k** [comment]
@jesseendahl totally tangent, but you ought to look into https://github.com/binford2k/binford2k-node_encrypt if you're worried about secrets in your catalog.

**Comment by rnelson0** [comment]
Closing this as it is beyond the scope of puppet-lint. Thanks!
