### ISSUE TITLE
Critical error on Atom initialization

### ISSUE THREAD

**Issue by mkowalski** [rodjek/puppet-lint#460]
Hi,

When running Atom following error is shown (screen attached)

> 'puppet-lint' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

Of course everything is installed, as the plugin works correctly, I just have to close the error message and the Console which is being shown because of it.

Configuration:

- OSX El Capitan
- Atom 1.4.1
- linter 1.11.3
- linter-puppet-lint 0.6.2

<img width="1440" alt="capture d ecran 2016-02-01 a 17 01 33" src="https://cloud.githubusercontent.com/assets/2862927/12722510/84f809f0-c905-11e5-936c-24afe409624e.png">

**Comment by matthewayala** [comment]
I had the same issue on windows, I had to specify the exact path to puppet-lint in the "linter-puppet-lint" add-on settings.

**Comment by rnelson0** [comment]
@mkowalski did Matthew's solution work for you?

**Comment by mkowalski** [comment]
Yep, it works now with path specified manually
