### ISSUE TITLE
Error: "Variable in single quoted string" or "Double quoted string without variable" - syntax?

### ISSUE THREAD

**Issue by Spreadcat** [rodjek/puppet-lint#463]
Hi,

Based on [this](http://ask.puppetlabs.com/question/24193/exec-for-loop/) issue on ask.puppetlabs.com I'd like to follow up on the problem with the syntax within an Exec-command:

The goal was running a for loop in an exec-command -parameter in order to create some directories. The following comand could not be modified without getting a puppet-lint warning:

**Alternative 1**:

    exec {'test':
      command => "for i in {00..99}; do c=000\$i; /bin/mkdir -p /tmp/data/\${c: -2}; done",
      provider => shell,
    }

**Alternative 2**:

    exec {'test':
      command => 'for i in {00..99}; do c=000$i; /bin/mkdir -p /tmp/data/${c: -2}; done',
      provider => shell,
    }

Either alternative 1 or alternative 2 is triggering a puppet-lint warning. Using alternative 1 without the escaped variables will render the command inoperable, since puppet is expanding the variable into *nil*.

What would be the way to resolve this issue? The issue of "double quote string without variable' seems to me the lower priority in linting. I would therefore disable that check prior to the check for variables in single quoted strings.

**Comment by rnelson0** [comment]
@Spreadcat That is a difficult syntax to catch without triggering too many alerts or none at all. You can use a [control comment](http://puppet-lint.com/controlcomments/), such as `# lint:ignore:double_quoted_strings`, to catch only those lines or segments where you want to ignore the lint check. Do you think that would be sufficient?

**Comment by Spreadcat** [comment]
Yes, I think that would be suffice. I was not aware of the control comment - thank you for pointing that out to me. This problem only occured once to me so far, so disabling the linting only for those lines is totally fair.
