### ISSUE TITLE
Question: using config file, with custom path

### ISSUE THREAD

**Issue by jeff1evesque** [rodjek/puppet-lint#466]
I am currently implementing the following lines within my `.travis.yml`:

```
...
install:
  - gem install puppet-lint
...
script:
  - puppet-lint --no-ensure_first_param-check --no-autoloader_layout-check --no-variable_scope-check puppet/environment/development/manifests
  - puppet-lint --no-ensure_first_param-check puppet/environment/development/modules
...
```

The [documentation](https://github.com/rodjek/puppet-lint#puppet-lint-1) states:

>puppet-lint will also check for a `.puppet-lint.rc` file in the current directory and your home directory and read in flags from there, so if you wanted to always skip the hard tab character check, you could create `~/.puppet-lint.rc` containing

>
```
--no-hard_tabs-check
```

However, I'm curious if I can implement a similar implementation within my `.travis.yml`, instead of disabling checks inline, within the `.travis.yml`:

```
...
script:
  - puppet-lint --config /path/to/.puppet-lint.rc puppet/environment/development/manifests
...
```

**Note:** I'm hoping to have `/path/to/.puppet-lint.rc` not be in the current, or home directory.

**Comment by rnelson0** [comment]
@jeff1evesque While you might be able to achieve this locally, it is unlikely Travis CI could be made to find a file outside of your git repo without serious contortions. However, that is not an issue with puppet-lint itself. You may have some success on IRC researching an answer. I suggest you look at using a `Gemfile` and `Rakefile` to get started.

**Comment by jeff1evesque** [comment]
What about:

```
...
script:
  - puppet-lint --config /path/to/local/git/repo/custom-directory/.puppet-lint.rc puppet/environment/development/manifests
...
```
