### ISSUE TITLE
Strange error about indent with comments

### ISSUE THREAD

**Issue by dioni21** [rodjek/puppet-lint#475]
Let me try to explain this with examples.

The code below reports 4 (four) errors:

```
class mymodule::test {
  file {
    '1':    # Comment 1
      ensure => file,  # ensure present
      ;
    '3':
      ensure => file,  # ensure present
      ;
  }
  file { '2': # This is ok...
    ensure => file,  # ensure present
  }
}
```

To work around, just remove the first comment:

```
class mymodule::test {
  file {
    '1':
      ensure => file,  # ensure present
      ;
    '3':
      ensure => file,  # ensure present
      ;
  }
  file { '2': # This is ok...
    ensure => file,  # ensure present
  }
}
```

Tested with yesterday's master

**Comment by rodjek** [comment]
I believe this error is coming from a 3rd party plugin (https://github.com/relud/puppet-lint-strict_indent-check). You'll need to open an issue on that repo to report the problem.
