### ISSUE TITLE
Start a CHANGELOG, make updates part of the build workflow

### ISSUE THREAD

**Issue by rnelson0** [rodjek/puppet-lint#479]
There is no `CHANGELOG`, which leaves users having to read the Releases info from GitHub. Start a log based on 2.0.0.

**Comment by ghoneycutt** [comment]
Since it is a major version change, any breaking changes should be documented so people understand what the big changes are from v1 to v2.

**Comment by rnelson0** [comment]
A full changelog was added via #481. I'm going to keep this open till we can add the generator as part of the workflow.

**Comment by 3flex** [comment]
This workflow should include updates to the changelog on the github page, if that's going to continue to be maintained.

**Comment by rnelson0** [comment]
Oof, did not realize there's http://puppet-lint.com/changelog/ as well. I will either update that or point to the github link.

**Comment by rnelson0** [comment]
The github change log generator is now available when using bundler and is part of the workflow. The change log link in the gh-pages site points to the real change log. Closing.
