### ISSUE TITLE
Error fixing indent in possion 0

### ISSUE THREAD

**Issue by DrOwl** [rodjek/puppet-lint#489]
I am having an issue where if i let lint fix an error like "WARNING: indent should be 2 chars and is 0 on line 1" it tends to fix it incorrectly as it adds the 2 chars at possession 1  instead of 0.

E.g.

=== Original file ===
class agent(
$group = "",
$server = "",
$serial = "",
$service_name =  "",
$server_ip = "",
$version = "",
$enabled = true,
){

=== Fixed file ===
 
class agent(
$  group = '',
$  server = '',
$  serial = '',
$  service_name =  '',
$  server_ip = '',
$  version = '',
$  enabled = true,
){

== Example runs ==

$ puppet-lint init.pp 
./manifests/init.pp - WARNING: indent should be 2 chars and is 0 on line 1
./manifests/init.pp - WARNING: indent should be 2 chars and is 0 on line 2
./manifests/init.pp - WARNING: indent should be 2 chars and is 0 on line 3
./manifests/init.pp - WARNING: indent should be 2 chars and is 0 on line 4
./manifests/init.pp - WARNING: indent should be 2 chars and is 0 on line 5
./manifests/init.pp - WARNING: indent should be 2 chars and is 0 on line 6
./manifests/init.pp - WARNING: indent should be 2 chars and is 0 on line 7

 
$ puppet-lint -f init.pp 
./manifests/init.pp - FIXED: indent should be 2 chars and is 0 on line 1
./manifests/init.pp - FIXED: indent should be 2 chars and is 0 on line 2
./manifests/init.pp - FIXED: indent should be 2 chars and is 0 on line 3
./manifests/init.pp - FIXED: indent should be 2 chars and is 0 on line 4
./manifests/init.pp - FIXED: indent should be 2 chars and is 0 on line 5
./manifests/init.pp - FIXED: indent should be 2 chars and is 0 on line 6
./manifests/init.pp - FIXED: indent should be 2 chars and is 0 on line 7

$ puppet-lint init.pp 
/var/lib/gems/2.1.0/gems/puppet-lint-trailing_newline-check-1.0.0/lib/puppet-lint/plugins/check_trailing_newline.rb:5:in `check': undefined method `type' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.1.0/gems/puppet-lint-2.0.0/lib/puppet-lint/checkplugin.rb:21:in `run'
	from /var/lib/gems/2.1.0/gems/puppet-lint-2.0.0/lib/puppet-lint/checks.rb:58:in `block in run'
	from /var/lib/gems/2.1.0/gems/puppet-lint-2.0.0/lib/puppet-lint/checks.rb:56:in `each'
	from /var/lib/gems/2.1.0/gems/puppet-lint-2.0.0/lib/puppet-lint/checks.rb:56:in `run'
	from /var/lib/gems/2.1.0/gems/puppet-lint-2.0.0/lib/puppet-lint.rb:174:in `run'
	from /var/lib/gems/2.1.0/gems/puppet-lint-2.0.0/lib/puppet-lint/bin.rb:59:in `block in run'
	from /var/lib/gems/2.1.0/gems/puppet-lint-2.0.0/lib/puppet-lint/bin.rb:56:in `each'
	from /var/lib/gems/2.1.0/gems/puppet-lint-2.0.0/lib/puppet-lint/bin.rb:56:in `run'
	from /var/lib/gems/2.1.0/gems/puppet-lint-2.0.0/bin/puppet-lint:7:in `<top (required)>'
	from /usr/local/bin/puppet-lint:23:in `load'
	from /usr/local/bin/puppet-lint:23:in `<main>'

$ ruby --version
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
$ puppet-lint -v
puppet-lint 2.0.0
$ uname -a
Linux e0307280 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
$ cat /etc/debian_version 
8.5
===================

This happed with an older version of lint too (1.1.0). I haven't seen any other bug reports for this so i am guessing something is strange with my setup. Any suggesions as how to debug this issue?

**Comment by rnelson0** [comment]
@DrOwl I do not see any matching check for the warning you are encountering inside puppet-lint's core checks. Can you provide the list of puppet-link checks you are using? I assume either `gem list | grep lint` or `bundle exec gem list | grep lint` will provide this. I suspect the issue may be in one of the external checks.

**Comment by DrOwl** [comment]
@rnelson0 
Arr this explains why I could not find the error description in the lint code:
The check is puppet-lint-strict_indent-check (2.0.1) by @relud 

In the fix part of that module "problem[:token].next_token.value" seems to be missing the first char in this example the "$"

===============
# gem list | grep lint
puppet-lint (2.0.0, 1.1.0)
puppet-lint-absolute_template_path (1.0.0)
puppet-lint-leading_zero-check (0.1.1, 0.1.0)
puppet-lint-roles_and_profiles-check (0.1.0)
puppet-lint-strict_indent-check (2.0.1)
puppet-lint-trailing_newline-check (1.0.0)
puppet-lint-unquoted_string-check (0.3.0, 0.2.5)
puppet-lint-variable_contains_upcase (1.0.0)

**Comment by rnelson0** [comment]
I think the issue might be [here](https://github.com/relud/puppet-lint-strict_indent-check/blob/master/lib/puppet-lint/plugins/check_strict_indent.rb#L137), it may need to read `column -1`, or in the fix it should say `prev_token`, etc. However, this is an external plugin and you should open an issue with relud to diagnose this, so I am closing this issue. Thanks!
