### ISSUE TITLE
question: 1.1.0 --> 2.0.0 new checks

### ISSUE THREAD

**Issue by mschuchard** [rodjek/puppet-lint#499]
I am the the maintainer of the AtomLinter package for PuppetLint and I had already implemented something for the change from 80 chars to 140 chars, but other than that I see nothing about new checks in the CHANGELOG. Were any checks added or removed? I would appreciate a quick yes/no, and a quick list would be even more appreciated.

**Comment by rnelson0** [comment]
No, there were no net-new checks, only the rename of `80chars` to `140chars` as documented [here](https://github.com/rodjek/puppet-lint/blob/master/CHANGELOG.md#200-2016-06-22).

**Comment by mschuchard** [comment]
Great, thanks for the info.
