### ISSUE TITLE
puppet-lint -f bug in mac machine

### ISSUE THREAD

**Issue by arunsingh** [rodjek/puppet-lint#532]
MacBook:puppet2-7-23 livestream$ gem pristine executable-hooks --version 1.3.2
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
Error loading RubyGems plugin "/Users/livestream/.rvm/gems/ruby-1.9.3-p551@global/gems/executable-hooks-1.3.2/lib/rubygems_plugin.rb": cannot load such file -- executable-hooks/wrapper (LoadError)
Error loading RubyGems plugin "/Users/livestream/.rvm/gems/ruby-1.9.3-p551@global/gems/gem-wrappers-1.2.7/lib/rubygems_plugin.rb": cannot load such file -- gem-wrappers (LoadError)
Restoring gems to pristine condition...
Building native extensions.  This could take a while...
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/ext/builder.rb:76: warning: Insecure world writable dir /usr/local in PATH, mode 040777
ERROR:  While executing gem ... (Gem::Ext::BuildError)
    ERROR: Failed to build gem native extension.

    current directory: /Users/livestream/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/executable-hooks-1.3.2/ext/wrapper_installer
/usr/local/opt/ruby/bin/ruby -r ./siteconf20160817-33894-1qy0cch.rb extconf.rb
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
/Users/livestream/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:71:in `initialize': Permission denied @ rb_sysopen - /usr/local/Cellar/ruby/2.3.1/bin/rake (Errno::EACCES)
	from /Users/livestream/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:71:in `open'
	from /Users/livestream/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:71:in `block in try_to_fix_binstubs'
	from /Users/livestream/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:69:in `map'
	from /Users/livestream/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:69:in `try_to_fix_binstubs'
	from /Users/livestream/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:46:in `block in execute_no_wrapper'
	from /Users/livestream/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:44:in `each'
	from /Users/livestream/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:44:in `execute_no_wrapper'
	from extconf.rb:19:in `<main>'
puppet-lint 2.0.0
rake 0.9.2.2

extconf failed, exit code 1

Gem files will remain installed in /Users/livestream/.rvm/gems/ruby-1.9.3-p551@global/gems/executable-hooks-1.3.2 for inspection.
Results logged to /Users/livestream/.rvm/gems/ruby-1.9.3-p551@global/extensions/x86_64-darwin-14/2.3.0/executable-hooks-1.3.2/gem_make.out
MacBook:puppet2-7-23 livestream$ puppet-lint -f package/manifests/ntp.pp
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
/Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/plugins/check_whitespace.rb:151:in `*': negative argument (ArgumentError)
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/plugins/check_whitespace.rb:151:in `fix'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checkplugin.rb:41:in `block in fix_problems'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checkplugin.rb:38:in `each'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checkplugin.rb:38:in `fix_problems'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checks.rb:68:in `block in run'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checks.rb:67:in `each'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checks.rb:67:in `run'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint.rb:174:in `run'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/bin.rb:59:in `block in run'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/bin.rb:56:in `each'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/bin.rb:56:in `run'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/bin/puppet-lint:7:in `<top (required)>'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/bin/puppet-lint:23:in `load'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/bin/puppet-lint:23:in `<main>'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
MacBook:puppet2-7-23 livestream$ gem pristine gem-wrappers --version 1.2.7
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
Error loading RubyGems plugin "/Users/livestream/.rvm/gems/ruby-1.9.3-p551@global/gems/gem-wrappers-1.2.7/lib/rubygems_plugin.rb": cannot load such file -- gem-wrappers (LoadError)
Restoring gems to pristine condition...
Building native extensions.  This could take a while...
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/ext/builder.rb:76: warning: Insecure world writable dir /usr/local in PATH, mode 040777
Restored gem-wrappers-1.2.7
MacBook:puppet2-7-23 livestream$ puppet-lint -f package/manifests/ntp.pp
/Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/plugins/check_whitespace.rb:151:in `*': negative argument (ArgumentError)
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/plugins/check_whitespace.rb:151:in `fix'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checkplugin.rb:41:in `block in fix_problems'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checkplugin.rb:38:in `each'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checkplugin.rb:38:in `fix_problems'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checks.rb:68:in `block in run'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checks.rb:67:in `each'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checks.rb:67:in `run'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint.rb:174:in `run'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/bin.rb:59:in `block in run'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/bin.rb:56:in `each'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/bin.rb:56:in `run'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/bin/puppet-lint:7:in `<top (required)>'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/bin/puppet-lint:23:in `load'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/bin/puppet-lint:23:in `<main>'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
MacBook:puppet2-7-23 livestream$ puppet-lint --fix package/manifests/ntp.pp
/Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/plugins/check_whitespace.rb:151:in `*': negative argument (ArgumentError)
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/plugins/check_whitespace.rb:151:in `fix'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checkplugin.rb:41:in `block in fix_problems'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checkplugin.rb:38:in `each'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checkplugin.rb:38:in `fix_problems'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checks.rb:68:in `block in run'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checks.rb:67:in `each'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/checks.rb:67:in `run'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint.rb:174:in `run'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/bin.rb:59:in `block in run'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/bin.rb:56:in `each'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/lib/puppet-lint/bin.rb:56:in `run'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/gems/puppet-lint-2.0.0/bin/puppet-lint:7:in `<top (required)>'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/bin/puppet-lint:23:in `load'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/bin/puppet-lint:23:in `<main>'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
	from /Users/livestream/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
MacBook:puppet2-7-23 livestream$

**Comment by rnelson0** [comment]
@arunsingh I'm confused by the large amount of output. Can you better describe the issue, and format the output so it's more legible and focused on the puppet-lint issues (rather than the other gems shown).

I also notice the string `puppet2-7-23` - does that mean you are running puppet 2.7.23?

**Comment by binford2k** [comment]
This looks to me like a problem with your gem environment. The puppet-lint gem works fine using rvm and ruby 1.9 here. You will need the Xcode command-line tools to compile any gems with native extensions, and you may also need some development libraries, which can be installed with Homebrew.

Can you clean this up and describe what the actual problem is?
