### ISSUE TITLE
Automatically fix errors bug?

### ISSUE THREAD

**Issue by apazga** [rodjek/puppet-lint#560]
Hi,

I was trying "Attemp to automatically fix errors" parameter, and after developing some Puppet modules I see one auto-fix that I think it's not OK.

If you have a file resource with the following source:
`source  => "puppet:///organization/${::environment}/modules/${module_name}/tutorial",`

"Auto-fix" replace it by:
`source  => "puppet:///modules/organization/${::environment}/modules/${module_name}/tutorial",`

Giving the following output: "`FIXED: puppet:// URL without modules/ found on line 2`"

So my module failed. Note that I'm using here a puppet server fileserver URL, not "files" folder inside a module.

Hope it helps. If you think that this wrong behaviour is my fault, please tell me!

Best regards!
Abel.

**Comment by rnelson0** [comment]
@apazga This is functioning as intended. Please check out [controlcomments](http://puppet-lint.com/controlcomments/) for [puppet_url_without_modules](http://puppet-lint.com/checks/puppet_url_without_modules/). You may disable this check globally, per block, or per line.

I will also be opening a ticket to track this plugin alongside others that are candidates to be disabled by default. It is considered a best practice by some but is not part of the style guide as far as I can tell. Thanks!
