### ISSUE TITLE
unquoted_node_name crash when curly braces missing

### ISSUE THREAD

**Issue by paran1** [rodjek/puppet-lint#582]
I made a typo when writing a test case for another issue I reported, and ran into this crash.

The following two examples of obviously incorrect puppet code both make puppet-lint fail in the same way:
```
$ cat empty_node1.pp 
node
$ cat empty_node2.pp 
node 'foo'
```
Expected result: syntax error.

Actual result: crash
```
$ puppet-lint empty_node1.pp
/usr/lib/ruby/vendor_ruby/puppet-lint/plugins/check_nodes.rb:13:in `block in check': bad value for range (ArgumentError)
	from /usr/lib/ruby/vendor_ruby/puppet-lint/plugins/check_nodes.rb:8:in `each'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/plugins/check_nodes.rb:8:in `check'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/checkplugin.rb:21:in `run'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/checks.rb:58:in `block in run'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/checks.rb:56:in `each'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/checks.rb:56:in `run'
	from /usr/lib/ruby/vendor_ruby/puppet-lint.rb:173:in `run'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/bin.rb:59:in `block in run'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/bin.rb:56:in `each'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/bin.rb:56:in `run'
	from /usr/bin/puppet-lint:7:in `<main>'
$ 
```
The crash is avoided by disabling the unquoted_node_name check, then we only get the warning about node definition (#580).
```
$ puppet-lint --no-unquoted_node_name-check empty_node1.pp
WARNING: code outside of class or define block - node on line 1
```

Tested with puppet-lint 2.0.2 and latest master (041b4303108309159e181092c883d2e6b8413649).

**Comment by rnelson0** [comment]
@paran1 Check out https://github.com/rodjek/puppet-lint/tree/validation. This should result in puppet-lint refusing to run because it's a linter, not a syntax checker. Please verify with your original sources.

**Comment by paran1** [comment]
That catches the problem for all my examples.
