### ISSUE TITLE
Add a plugable way to check files/templates

### ISSUE THREAD

**Issue by vStone** [rodjek/puppet-lint#588]
It would be useful to have some checks on these files too and have them report in the same way as puppet-lint does having a single way to provide style information.

In stead of being lexer/token based, should probably be file-type based (with the possibility to override the default patterns).

My first use case would be to check that people have a 'File managed by puppet' comment in the file with the correct module and path included.

**Comment by ghoneycutt** [comment]
I agree this could be useful though it is out of scope for puppet-lint which is a tool to ensure that Puppet manifests comply with the Puppet Style Guide.

**Comment by rnelson0** [comment]
I agree, this is a good idea but beyond the scope of puppet-lint. Maybe try a pre-commit check like https://github.com/mattiasgeniar/puppet-pre-commit-hook or https://github.com/drwahl/puppet-Git-hooks?
