### ISSUE TITLE
Pattern type results in syntax error message

### ISSUE THREAD

**Issue by taladar** [rodjek/puppet-lint#601]
e.g. in defined type on parameter

`
  , Pattern[/^[2345][0-9][0-9]$/] $instance_expected_http_status_code = '200'
`

or a class parameter line

`
    Pattern[/^[01]\.[0-9]\.[0-9]$/] $version = "1.0.7"
`

or a defined type parameter

`
  , Pattern[/[^`~!$%^&*|'"<>?,()]+/] $description`

**Comment by rnelson0** [comment]
Can you provide some more information on how to reproduce this? Using puppet-lint 2.0.2, a sample file containing a pattern type seems to work:
```
class test (
  Pattern[/^[01]\.[0-9]\.[0-9]$/] $version = "1.0.7",
) { }

$ puppet-lint 601.pp
ERROR: test not in autoload module layout on line 1
WARNING: class not documented on line 1
WARNING: double quoted string containing no variables on line 2
```

**Comment by taladar** [comment]
I am sorry, it seems there was an old version of puppet-lint earlier in my path (1.x). The current version does not seem to return these errors.
