### ISSUE TITLE
Warning and error classification

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [rodjek/puppet-lint#614]
The distinction between errors and warning seems to be set quite subjective. Is there a way to change what is considered an error and what a warning?

For example, an unquoted file is to me more important and error-prone than trailing whitespace.

**Comment by rodjek** [comment]
@hubertgrzeskowiak In general it is determined from the [style guide](https://docs.puppet.com/guides/style_guide.html), interpreting the RFC2119 terms `MUST` and `SHOULD` as errors and warnings respectively.

**Comment by hubertgrzeskowiak** [comment]
I see. Thanks.

**Comment by rnelson0** [comment]
@hubertgrzeskowiak Check out how to [disable checks](https://github.com/rodjek/puppet-lint/#disabling-checks) and use [control comments](http://puppet-lint.com/controlcomments/) as it sounds like you may not want trailing whitespace checks at all.

**Comment by hubertgrzeskowiak** [comment]
Hi @rnelson0 and thanks for the links. I don't want to disable any checks, but I pay more attention to errors than to warnings and I'm not sure I agree with the authors of the original style guide regarding the classification. Some rules mitigate the risk of bugs, others improve readability, and even others, like the trailing whitespace, are niticking on a high level. IMHO the keywords from the spec should somehow reflect these levels.

**Comment by rnelson0** [comment]
@hubertgrzeskowiak I think I understand your concern better now. There is currently a [Puppet Epic ticket](https://tickets.puppetlabs.com/browse/DOCUMENT-266) to update the style guide. We have worked with Puppet on some aspects of the style guide, and when we see the updates reflected live on the site, we will update checks and maybe even disable some by default. The first step would be raising a ticket or commenting on existing ones to get the style guide updated. Once the update is live, then open an issue here to update the relevant check(s).

**Comment by hubertgrzeskowiak** [comment]
I've created a pull request with it now. If you (or other devs) think that this change needs more discussion or voting, I'll open a JIRA issue.
