### ISSUE TITLE
Determine triage/planning meeting time and schedule

### ISSUE THREAD

**Issue by rnelson0** [rodjek/puppet-lint#623]
As discussed in December 2016, we would like to have regular puppet-lint triage/planning meetings. No specific schedule or time was agreed upon. A bi-monthly schedule suggested, which seems like a good starting point. Time is more difficult as we had attendees from both coasts of the US as well as Australia. Assuming a bi-monthly schedule starting in February, what days and times work for everyone? (all times in UTC please)

I will update this post with all times suggested so it's easily visible.

3rd Thursday of every other month, 2100 UTC (rnelson0)

**Comment by binford2k** [comment]
3rd Thursday of every other month, 2100 UTC works for me

**Comment by rnelson0** [comment]
Next Thursday will be the 3rd Thursday of February. I'll announce the triage meeting through puppet-dev today unless anyone objects. Thanks!

**Comment by rnelson0** [comment]
I've been informed that next week, Puppet employees will not be available at that time. I'll set it up for 2/23 @ 2100 UTC instead.

**Comment by rodjek** [comment]
I think this can be closed out now.
