### ISSUE TITLE
Release 2.2.0 planning and discussion

### ISSUE THREAD

**Issue by irgeek** [rodjek/puppet-lint#668]
Checks for voxpupuli/puppet-lint-param-docs#8 are currently failing due to a missing dependency that was introduced in rodjek/puppet-lint@3cd391d2. The error was fixed in rodjek/puppet-lint@345b211e but that commit hasn't been included in a release yet.

Can you let me know what the timeframe for the next release is, please? I don't need exact dates or anything, just a general idea of weeks/months/whatever.

Thanks!

**Comment by rodjek** [comment]
@irgeek I'm planning on a release in the next 2 weeks (which will probably be 2.2.0)

**Comment by rnelson0** [comment]
@rodjek I created the milestone 2.2.0, if you want to tag issues/PRs that we want to make sure are included.

**Comment by rodjek** [comment]
@rnelson0 I've added all the issues & PRs that I'd like to be closed before the 2.2.0 release to the milestone and gone through all the merged PRs since the 2.1.1 release and added all the issues they closed so we have an easier time writing the changelog

**Comment by rodjek** [comment]
OK, I've got PRs open for all the remaining open issues marked for 2.2.0, so once they're reviewed and merged and we can push out the new release.

**Comment by rodjek** [comment]
@irgeek 2.2.0 is out now which includes the fix you needed
