### ISSUE TITLE
Check `arrow_on_right_operand_line` is undocumented.

### ISSUE THREAD

**Issue by irgeek** [rodjek/puppet-lint#688]
Hi folks.

It seems the 2.2.0 release fixed a bug that had been suppressing the `arrow_on_right_operand_line ` check in our code bases. When I saw it pop up this morning I went to investigate and noticed it doesn't appear to be documented on the [checks](http://puppet-lint.com/checks/) page. I looked at submitting a pull request, but it looks like the docs might be auto-generated.

**Comment by rnelson0** [comment]
@irgeek the site docs aren't auto updated, so a PR would be welcomed. Thanks for pointing out this oversight, and apologies that it caught you up!

**Comment by rodjek** [comment]
Sorry about that @irgeek, I've updated the site and the README to include this new check.
