### ISSUE TITLE
Mangled file after running puppet-lint due to chained function call

### ISSUE THREAD

**Issue by gettalong** [rodjek/puppet-lint#703]
Given the following test file:

~~~ puppet
file {'/tmp/dir':
  content => "This is ${fqdn.upcase}",
}
~~~

When running "puppet-lint", no error is shown which is the correct behaviour. However, when running "puppet-lint --fix", the content is changed to

~~~ puppet
file {'/tmp/dir':
  content => "This is ${fqdn}.upcase",
}
~~~

The difference is that `${fqdn.upcase}` gets changed into `${fqdn}.upcase` which is not equivalent and leads to errors.

Tested with puppet-lint 2.2.1.

**Comment by ghoneycutt** [comment]
+1 confirming this issue
