### ISSUE TITLE
ERROR: Syntax error on Ampersand

### ISSUE THREAD

**Issue by patsevanton** [rodjek/puppet-lint#711]
**cat test.erb** 
`run command <%= @variable %> 2>&1`

**puppet-lint test.erb** 
`ERROR: Syntax error (try running `puppet parser validate <file>`) on line 1`

**puppet-lint -v**
`puppet-lint 2.2.1`

**Comment by rnelson0** [comment]
puppet-lint only checks puppet code, not ERB templates.
