### ISSUE TITLE
Puppet-lint --fix silently removes necessary $ inside double quoted strings

### ISSUE THREAD

**Issue by 2fa** [rodjek/puppet-lint#773]
It doesn't showing this at all (even with error_level all), just silently removes $ inside the strings. This leads to manifest fails.

For example:

test.pp

```ruby
$foo = 25

$bar = "${$foo + 200}"

notice($bar)
```

> puppet apply test.pp
> Notice: Scope(Class[main]): 225

After puppet-lint --fix test.pp

```ruby
$foo = 25

$bar = "${foo + 200}"

notice($bar)
```

> puppet apply test.pp
> Error: Evaluation Error: The value 'foo' cannot be converted to Numeric.

It can be related to #747 
Also consider #675

**Comment by rodjek** [comment]
Fixed by #846
