### ISSUE TITLE
Configuration's ignore_paths is not respected

### ISSUE THREAD

**Issue by jarro2783** [rodjek/puppet-lint#774]
In `puppet-lint-2.3.3`, setting `PuppetLint.configuration.ignore_paths` is ignored.

Our rake task does this:
```
PuppetLint.configuration.ignore_paths = [
  'ext_modules/**/*',
  'spec/fixtures/**/*',
  'vendor/**/*',
]
PuppetLint::RakeTask.new(:puppet_lint)
```

and all of those paths are linted.

I think it was broken by #762, which fixed setting `ignore_paths` in the task body, but broke reading it from outside.

The reason is that the default is
```
@ignore_paths = []
```
which when evaluated here:
```
@ignore_paths ||= PuppetLint.configuration.ignore_paths
```
is truthy and therefore is never set to `PuppetLint.configuration.ignore_paths`.

**Comment by rodjek** [comment]
Resolved by #777

**Comment by joshuaspence** [comment]
Any plans to release a new version soon now that this issue has been resolved?

**Comment by rodjek** [comment]
@joshuaspence Yep, this will be part of the 2.3.4 later this week.

**Comment by joshuaspence** [comment]
Bump. It seems that 2.3.4 still has not yet been released.

**Comment by alexharv074** [comment]
It's 4 months now. A workaround:

```
# Version 2.3.3 introduced a bug in ignore_paths.                              
#                                                                              
gem 'puppet-lint', '< 2.3.3', :require => false
```
