### ISSUE TITLE
2.3.3 - Rakefile's ignore_paths not respected

### ISSUE THREAD

**Issue by toteva** [rodjek/puppet-lint#784]
Hi

We are experiencing the still the problem with puppet-lint 2.3.3.
-bash-4.2$ cat ../ci/Gemfile.lock | grep puppet-lint
puppet-lint (2.3.3)
puppet-lint-absolute_classname-check (0.2.4)
puppet-lint (>= 1.0, < 3.0)
puppet-lint-classes_and_types_beginning_with_digits-check (0.1.2)
puppet-lint (>= 1.0, < 3.0)
puppet-lint-leading_zero-check (0.1.1)
puppet-lint (>= 1.0, < 3.0)
puppet-lint-trailing_comma-check (0.3.2)
puppet-lint (>= 1.0, < 3.0)
puppet-lint-unquoted_string-check (0.3.0)
puppet-lint (>= 1.0, < 3.0)
puppet-lint-variable_contains_upcase (1.2.0)
puppet-lint (>= 1.0, < 3.0)
puppet-lint-version_comparison-check (0.2.1)
puppet-lint (>= 1.0, < 3.0)
puppet-lint (~> 2.0)
puppet-lint-absolute_classname-check
puppet-lint-classes_and_types_beginning_with_digits-check
puppet-lint-leading_zero-check
puppet-lint-trailing_comma-check
puppet-lint-unquoted_string-check
puppet-lint-variable_contains_upcase
puppet-lint-version_comparison-check
-bash-4.2$ cat ../ci/Rakefile
...........
PuppetLint.configuration.ignore_paths = ["manifests/app.pp"]
PuppetLint.configuration.fail_on_warnings = true
desc 'Run'
task test: [
:lint,
]
-bash-4.2$ .... 'bundle exec rake --rakefile ../ci/Rakefile test'
manifests/app.pp - WARNING: missing trailing comma after last element on line 11

Thanks

Cheers
Zhechka

**Comment by toteva** [comment]
Any news on this?

**Comment by rodjek** [comment]
@toteva I'm not sure what problem you're referring to? From what you've pasted, puppet-lint has detected a problem in your manifest (using a community plugin), which is what it's supposed to do.

If that warning you pasted is in error, you should raise an issue with that plugin https://github.com/voxpupuli/puppet-lint-trailing_comma-check

**Comment by toteva** [comment]
Hi.

Not really. I did not mean the comma. I tried to build a simple example in order to report it here and I missed the comma.

The problem is that with puppet-lint 2.3.3 we have the following complaint from one of your users:

With Rakefile containing:

exclude_paths = %w(
  pkg/**/*
  vendor/**/*
  .vendor/**/*
  spec/**/*
  manifests/crab/**/*
  manifests/frontier/**/*
  manifests/cmsweb/**/*
)
PuppetLint.configuration.ignore_paths = exclude_paths
PuppetSyntax.exclude_paths = exclude_paths

then in the tests we see:

manifests/crab/schedd.pp:75:arrow_on_right_operand_line:WARNING:arrow should be on the right operand's line
manifests/crab/schedd.pp:77:arrow_on_right_operand_line:WARNING:arrow should be on the right operand's line
manifests/crab/schedd.pp:13:relative_classname_inclusion:WARNING:class included by relative name
manifests/crab/schedd/directories.pp:6:autoloader_layout:ERROR:createhomedirs not in autoload module layout
manifests/crab/schedd/directories.pp:6:nested_classes_or_defines:WARNING:defined type defined inside a class
manifests/crab/schedd/directories.pp:6:variable_scope:WARNING:top-scope variable being used without an explicit namespace

And we should not see any of those as all the "manifests/crab/**/*" should be ignored.

Cheers
Zhechka

**Comment by toteva** [comment]
Is it possible that it is related to the PuppetLint.configuration.fail_on_warnings = true?
