### ISSUE TITLE
WARNING: mode should be represented as a 4 digit octal value or symbolic mode on line 

### ISSUE THREAD

**Issue by cuky23** [rodjek/puppet-lint#786]
I like this test and would rather not filter it out.

it is failing on the following use case 
 mode => "${mode}"

where the mode of the file is set to a string in logic above.  can this be fixed or do i have to skip this test :(
sometimes I use the following
    if "${ftphome}" == "/var/www" {
          $mode = '2775'
    } elsif "${ftphome}" == "/home" {
          $mode = '0755'
    } else {
          $mode = '0755'
    }

**Comment by rnelson0** [comment]
@cuky23 We looked at the style guide, specifically https://puppet.com/docs/puppet/5.3/style_guide.html#file-modes, and it says `The file mode attribute should always be a quoted string, never an integer.` We have updated it to indicate that a variable is okay and that it should not be quoted. The docs take a while to build, so the change should be visible within the next 24 hours. So, `mode => "${mode}"` would still be considered improper, but `mode => $mode` would be proper. Does that help?

**Comment by cuky23** [comment]
Due to time constraints on the project I had this issue with , I just changed the code to force the mode inside an if. 

Having the lint just check for the Quoted string is fine with me, however it checking for 4-digits in a string was good for lint purposes.

**Comment by rnelson0** [comment]
@cuky23 The linter is not looking at the results of interpolation, so that's a bit beyond its scope.

The style guide is now updated. Thanks for pointing this out!
