### ISSUE TITLE
How to dump parsed manifest's classes and defined types as JSON?

### ISSUE THREAD

**Issue by desertkun** [rodjek/puppet-lint#793]
I am wondering if there's an option to make puppet-lint to output parsed classes, defined types, along with their parsed parameters, instead of checking for style issues?

I mean as long as this tool checks for style issues, it has to check the syntax first, right? And if so, is there a way to extract that intermediate data, for example, into JSON? 

I am trying to make a GUI tool that needs to know what classes and defined types the environment has (including their parameters), and this tool seems like is capable of providing that information, not sure how, however.

**Comment by rnelson0** [comment]
puppet-lint does NOT do any syntax validation, it leaves that to puppet. You can use `puppet parser validate <filename>` to get a pass/fail result, and you can leverage the puppet parser in Ruby to examine the catalog/AST directly, but that is entirely out of scope of the puppet-lint project.

I'm not sure what your GUI tool requires, but perhaps look at editor plugins, like VSCode and vim ([vim-puppet](https://github.com/rodjek/vim-puppet)), to see how they mark up syntax inline as you type, before it's even validated.
