### ISSUE TITLE
Create and publish a docker image for puppet-lint

### ISSUE THREAD

**Issue by ColinHebert** [rodjek/puppet-lint#794]
Currently the installation of puppetlint requires to use gem directly. It should be possible to provide a docker image that has the latest version of puppet-lint provided.

Why would you want that? Some tools start to rely more and more on docker to provide binaries rather than requiring developers to install the binary on their machine.
An example of that is Atom Beautifier (https://github.com/Glavin001/atom-beautify look for puppet on the page) which uses puppet-lint to format puppet files.

Rather than requiring the developer to install puppet-lint locally, the tool will do a `docker run --rm -v "$(pwd):/puppet" -w /puppet name_of_the_puppet_lint_image --fix`.

There are many other usecases, and the best proof of that would be doing a simple search for puppet-lint in dockerhub:
https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=puppet-lint&starCount=0

**Comment by mritzmann** [comment]
A Docker Image would be very useful. My Use Case would be to use puppet-lint in a GitLab-Ci. A finished Docker Image speeds up the process.

Here is an example for inspiration, how this is solved with hadolint (Dockerfile linter): https://github.com/hadolint/hadolint/blob/master/docs/INTEGRATION.md

**Comment by DavidS** [comment]
This has been addressed in #901
