### ISSUE TITLE
how to fix this error

### ISSUE THREAD

**Issue by 11071999** [rodjek/puppet-lint#800]
WARNING: linker: nokogiri.so: unused DT entry: type 0x6ffffef5 arg 0xb30

**Comment by rodjek** [comment]
@11071999 that looks like a problem with your nokogiri install, which is not related to puppet-lint. I haven't run into that issue before, so my only suggestion would be to remove nokogiri and reinstall it (`gem uninstall nokogiri && gem install nokogiri`).
