### ISSUE TITLE
Should validate that task names do not have conflicting implementations

### ISSUE THREAD

**Issue by glennsarti** [rodjek/puppet-lint#847]
The Puppet Forge will not allow modules to be uploaded that have conflicting task implementations due to https://tickets.puppetlabs.com/browse/FORGE-436 . This was due to older PE versions getting confused by tasks with the same name.  Newer PE versions are ok.

Puppet-Lint should at least issue a warning when it finds tasks that could have conflicting implementations

**Comment by rodjek** [comment]
This isn't really a Puppet manifest style issue, which is the primary concern of puppet-lint. This would be better suited as a PDK validation or a pre-publish check in puppetlabs_spec_helper like the `check:symlinks` rake task. That said, I'm pretty sure that the Forge now allows modules with multiple implementations of tasks, so it's probably a moot point now.
