### ISSUE TITLE
Content of heredocs should not be checked

### ISSUE THREAD

**Issue by mauricemeyer** [rodjek/puppet-lint#851]
I checked all open issues (especially #585), but there is none matching my specific problem.

In a [heredoc](https://puppet.com/docs/puppet/5.4/lang_data_string.html#heredocs), e.g.

```
$ldap = @(LDAP)
  AuthBasicProvider ldap
  AuthLDAPGroupAttributeIsDN on
  AuthLDAPGroupAttribute member
  AuthLDAPURL ldap://ldap.example.com/dc=de?uid?one?(uid=name-*) TLS
  |-LDAP
```

The content is still checked. This leads to:

* // comment found on line x
* unquoted resource title on line x 

for the `AuthLDAPURL` line.

My understanding would be that there should be no checks at all inside here-documents - or is that wrong?

**Comment by luksi1** [comment]
I just hit this too with a heredoc PEM public certificate. +1
