### ISSUE TITLE
puppet-lint parse error with double $

### ISSUE THREAD

**Issue by tomzombie** [rodjek/puppet-lint#871]
If you use $$variable = 0 it causes the parser to throw a console error. To reproduce create a file qwerty.pp and on the first line type `$$variable = 0`

[Linter] Error running Puppet-Lint Error: Try running `puppet parser validate <file>`

**Comment by tomzombie** [comment]
I ran `puppet parser validate qwerty.pp` and got

Error: This Variable has no effect. A value was produced and then forgotten (one or more preceding expressions may have the wrong form)
Error: Illegal variable name, The given name '' does not conform to the naming rule /^((::)?[a-z]\w*)*((::)?[a-z_]\w*)$/ 
Error: Language validation logged 2 errors. Giving up

"Giving up" makes me this this is expected behavior

**Comment by rodjek** [comment]
This is the expected behaviour for invalid syntax (suggesting that you run `puppet parser validate` to get more details on the syntax error)
