### ISSUE TITLE
Double quoted string containing variable named "node" mis-tokenized

### ISSUE THREAD

**Issue by seanmil** [rodjek/puppet-lint#897]
As of 2.4.0 a variable such as `${node}` is mis-tokenized as DQPRE, NODE, DQPOST instead of DQPRE, VARIABLE, DQPOST. This causes incorrect errors in (at least) the check_nodes/unquoted_node_name check of the form "WARNING: unquoted node name found"

**Comment by seanmil** [comment]
The issue actually seems to be broader. It appears that any variables named the same as a keyword in a double quoted string will be incorrectly tokenized. Please see referenced PR for an attempt that seems successful in addressing it.

**Comment by rodjek** [comment]
Fixed by #898
