### ISSUE TITLE
Puppetfile mod calls for Puppetforge modules with no version defined marked as wrong

### ISSUE THREAD

**Issue by jevon71-work** [rodjek/puppet-lint#916]
In the VSCode extension, the mod lines without version numbers are being marked as invalid - but this is acceptable behaviour for r10k, since the latest version will be downloaded if you do not specify a version.

```
forge "https://forge.puppetlabs.com"

mod 'puppetlabs/apache'
```

Am I doing something wrong with my settings?  I could not find any documentation which suggests a fix for this in the Extension docs here: https://puppet-vscode.github.io/docs/

**Comment by rodjek** [comment]
Hi @jevon71-work 

puppet-lint doesn't check the contents of your `Puppetfile`, it only operates on your Puppet manifest (`.pp`) files. I suggest you open on the [vscode extension](https://github.com/lingua-pupuli/puppet-vscode) as they'll be able to help you more than I can.
