### ISSUE TITLE
Lint for '

### ISSUE THREAD

**Issue by byronicle** [rodjek/puppet-lint#927]

**Comment by byronicle** [comment]
Hi,

When using a file server mount point such as `puppet:///installer_files/oracle.pkg:` puppet-lint flags `puppet_url_without_modules`. This is the correct syntax to use when using a file server mount point. 

To work around this issue, we have to either disable `puppet_url_without_modules` or add `# lint:ignore:puppet_url_without_modules` to the file.

Thanks,
Byron

**Comment by rodjek** [comment]
Yeah, I would recommend just disabling the check in your config. The idea behind the check was to help catch mistakes from Puppet beginners who generally don't have custom fileserver mounts. This check will be switched over to become opt-in in an upcoming release.
